language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"

install:
  - conda install --yes python=$TRAVIS_PYTHON_VERSION numpy scipy matplotlib six anaconda-client conda-build
  - pip install .
  - pip install boto3 zmq pytest mock python-coveralls

before_install:
  - BASE=https://repo.continuum.io/miniconda/Miniconda;
    END=-Linux-x86_64.sh;
    if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then VERSION=2-latest;
    elif [[ "$TRAVIS_PYTHON_VERSION" == "3.4" ]]; then VERSION=3-3.16.0;
    elif [[ "$TRAVIS_PYTHON_VERSION" == "3.5" ]]; then VERSION=3-4.2.12;
    elif [[ "$TRAVIS_PYTHON_VERSION" == "3.6" ]]; then VERSION=3-latest;
    fi;
    wget "$BASE$VERSION$END" -O miniconda.sh;
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
       export PATH=/home/travis/miniconda2/bin:$PATH;
    else
       export PATH=/home/travis/miniconda3/bin:$PATH;
    fi
  - conda update --yes -q conda
  # The next couple lines fix a crash with multiprocessing on Travis and are not specific to using Miniconda
  - sudo rm -rf /dev/shm
  - sudo ln -s /run/shm /dev/shm

script: pytest tests/

notifications:
  email:
    recipients:
      - tanner@semafor.ch
      - mauchle@semafor.ch
      - amsler@semafor.ch
    on_success: change
    on_failure: always

deploy:
  provider: pypi
  user: "$PYPI_USERNAME"
  password: "$PYPI_PASSWORD"
  distributions: "sdist bdist_wheel"
  on:
    tags: true

after_deploy:
  - ./conda_deploy.sh
